@startuml
start
:输入网址;
:发送GET请求;
:返回首页页面;
:显示首页页面;
:点击登录按钮;
:发送GET请求;
:返回登录页面;
:显示登录页面;
:输入用户名和密码;
:发送POST请求;
:查询用户信息;
if (用户名和密码匹配) then (是)
  :发送登录成功的响应;
  :显示登录成功的提示;
else (否)
  :发送登录失败的响应;
  :显示登录失败的提示;
endif

:点击新建文章按钮;
:发送GET请求;
:返回新建文章页面;
:显示新建文章页面;

:输入文章标题和内容;
:发送POST请求;
:插入文章数据;
if (插入成功) then (是)
  :发送新建成功的响应;
  :显示新建成功的提示;
else (否)
  :发送新建失败的响应;
  :显示新建失败的提示;
endif
stop
@enduml
