@startuml
start
:输入网址;
:发送GET请求;
:返回首页页面;
:显示首页页面;
:点击一篇文章标题;
:发送GET请求;
:查询文章数据;
:返回文章页面;
:显示文章页面;

:输入评论内容和个人信息;
:发送POST请求;
:插入评论数据;
if (插入成功) then (是)
  :发送发表成功的响应;
  :显示发表成功的提示;
else (否)
  :发送发表失败的响应;
  :显示发表失败的提示;
endif
stop
@enduml
