@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <b>x</b>
!define foreign_key(x) <color:blue>x</color>
hide methods
hide stereotypes

table(admin) {
  primary_key(id)
  username
  password_hash
}

table(category) {
  primary_key(id)
  name
}

table(post) {
  primary_key(id)
  title
  body
  timestamp
  can_comment
  foreign_key(category_id)
}

table(comment) {
  primary_key(id)
  author
  email
  site
  body
  from_admin
  reviewed
  timestamp
  foreign_key(post_id)
}

table(link) {
  primary_key(id)
  name
  url
}

post "1" *-- "0..1" category : has a
comment "0..*" -- "1" post : belongs to
@enduml
